all:
	bin/wall
	bin/wall red
	bin/wall green
	bin/wall paint
	bin/wall red paint
	bin/wall green paint
	bin/wall green red paint
	bin/wall corner
	bin/wall corner alarm
	bin/wall corner camera
	bin/wall corner install
	bin/wall corner alarm install
	bin/wall corner camera install
	bin/wall corner alarm camera install
	bin/wall ceiling
	bin/wall ceiling red
	bin/wall ceiling green
	bin/wall ceiling paint
	bin/wall ceiling red paint
	bin/wall ceiling green paint
	bin/wall ceiling green red paint
