all:
	bin/base red
	bin/base green
	bin/base paint
	bin/base red paint
	bin/base green paint
	bin/base green red paint
	bin/base corner alarm
	bin/base corner camera
	bin/base corner install
	bin/base corner alarm install
	bin/base corner camera install
	bin/base corner alarm camera install
