#!/usr/bin/env bash

function debug {
  if [[ -z "${DEBUG:-}" ]]; then
    return 0
  fi

  echo "$@"
}

function sub-chain {
  local nm_source="$1"; shift

  export SUB_MIDDLEWARE=" ${SUB_MIDDLEWARE:+${SUB_MIDDLEWARE} }${nm_source##*/} "
  export SUB_RMIDDLEWARE=" ${nm_source##*/}${SUB_MIDDLEWARE:+ ${SUB_MIDDLEWARE}} "

  case "${1:-}" in
    -*) true ;;
    *)
      for a in $SUB_RMIDDLEWARE; do
        local nm_env="___${a//-/_}"
        if [[ -n "${!nm_env:-}" ]]; then
          continue
        fi
        eval "$nm_env"=1
        debug "    trying ${a:+$a-}${1:-} ... $@" 1>&2
        if type -P "${a:+$a-}${1:-1}" >/dev/null; then
          debug "    found ${a:+$a-}${1:-}" 1>&2
          source sub "$a" "$@"
          return "$?"
        fi
      done
  esac

  for a in $SUB_RMIDDLEWARE; do
    local nm_env="____${a//-/_}"
    if [[ -n "${!nm_env:-}" ]]; then
      continue
    fi
    eval "$nm_env"=1
    debug "    trying $a ... $@" 1>&2
    if type -P "$a" >/dev/null; then
      debug "    found $a" 1>&2
      source sub "$a" "$@"
      return "$?"
    fi
  done

  debug "   not found" 1>&2
}

debug XXX "$BASH_SOURCE" sub-chain "$@" 1>&2
sub-chain "$@"
