#!/usr/bin/env bash

function middleware-sub {
  local nm_source="$1"; shift

  local nm_middleware
  for nm_middleware in ${SUB_MIDDLEWARE}; do
    if type -P "$a-${1:-}" 2>&-; then
      exec "${nm_middleware}-${1}" "${@:2}"
    fi
  done

  "${SUB_MIDDLEWARE%% *}" "$@" 
}

middleware-sub "$@"
