#!/usr/bin/env bash

function middleware-sub {
  local nm_source="$1"; shift

  local nm_middleware
  for nm_middleware in ${SUB_MIDDLEWARE}; do
    if [[ "$(which "${nm_middleware}-${1:-}" 2>&- || true)" ]]; then
      exec "${nm_middleware}-${1}" "${@:2}"
    fi
  done

  "${SUB_MIDDLEWARE%% *}" "$@" 
}

middleware-sub "$@"
